version: '3'

volumes:
  pg_data_production_kg:
  static_volume_kg:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production_kg:/var/lib/postgresql/data
  backend:
    image: hopedforluck/kittygram_backend
    env_file: .env
    volumes:
      - static_volume_kg:/backend_static
  frontend:
    image: hopedforluck/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume_kg:/frontend_static
  gateway:
    image: hopedforluck/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume_kg:/staticfiles/
    ports:
      - 9000:80