version: '3'

volumes:
  pg_data_kitgm:
  static_kitgm:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kitgm:/var/lib/postgresql/data
  backend:
    image: hopedforluck/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static_kitgm:/backend_static
  frontend:
    image: hopedforluck/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kitgm:/frontend_static
  gateway:
    image: hopedforluck/kittygram_gateway
    env_file: .env
    volumes:
      - static_kitgm:/staticfiles/
    ports:
      - 9000:80